default: &default
  adapter: postgresql
  encoding: unicod
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
 <<: *default
 database: nilo-os_development

test:
 <<: *default
 database: nilo-os_test

production:
  <<: *default
  database: nilo_production
  username: nilo
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
